name: Publish release

on:
  push:
    branches:
      - master
    paths:
      - "awscliv2/version.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U pip twine wheel
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          rm -rf build *.egg-info dist/*
          python setup.py build sdist bdist_wheel
          twine upload --non-interactive dist/*
